use serde::{Deserialize, Serialize};

pub mod metrics;
pub mod pid;
pub mod config;

pub use metrics::BenchmarkRecorder;
pub use config::ExperimentConfig;

/// The "Packet" generated by the sensor.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct SensorData {
    pub id: u64,
    pub timestamp: u64,    // Generation time (nanoseconds)
    
    // The specific fields required by your design
    pub force: f64,
    pub position: f64,
    pub temperature: f64,
}

/// The "Command" sent to the actuator.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct ActuatorCommand {
    pub sensor_id: u64,
    pub action_value: f64,
    pub timestamp: u64,
}

/// The "Feedback" sent back to the sensor/system.
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct Feedback {
    pub sensor_id: u64,
    pub status: ActuatorStatus,
    pub timestamp: u64,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq)]
pub enum ActuatorStatus {
    Normal,
    Correcting,
    EmergencyStop,
}